### ISSUE TITLE
How to enter Private Key Password ?

### ISSUE THREAD

**Issue by tugsjargal1** [AnhTVc/OpenVPN-IOS#20]
Dear AnhTVc,

You are doing GREAT!., We love to know your project is working well.

Our OpenVPN server does not use username and password authentication and uses only Private Key. 
How can I authenticate with private key ? 

When I run the app I got messages as below: 

-> Enter Private Key Password:
-> WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
-> Error: private key password verification failed
-> Exiting due to fatal error

Is there a way to authenticate with Private Key ?

Thank you so much.

**Comment by AnhTVc** [comment]
you can export private key to file config with option <key></key>
overwrite to udp.ovpn
