### ISSUE TITLE
OpenVPN Error - EXC_BAD_ACCESS (code=1, address=0x68)

### ISSUE THREAD

**Issue by cogphone** [AnhTVc/OpenVPN-IOS#29]
I am getting the below mentioned error, when I install the app

Thu Jul  4 19:07:56 2019 OpenVPN 2.3_git arm-apple-darwin [SSL (OpenSSL)] [MH] [IPv6] built on Jun 16 2017
Thu Jul  4 19:07:56 2019 WARNING: file '/var/containers/Bundle/Application/18C48C87-E43F-463A-867A-56DB5A608343/openvpn.app/pass.txt' is group or others accessible
Thu Jul  4 19:07:56 2019 Control Channel Authentication: tls-auth using INLINE static key file
Thu Jul  4 19:07:56 2019 Attempting to establish TCP connection with [AF_INET]45.95.5.157:1194 [nonblock]
Thu Jul  4 19:07:57 2019 TCP connection established with [AF_INET]45.95.5.157:1194
Thu Jul  4 19:07:57 2019 TCPv4_CLIENT link local: [undef]
Thu Jul  4 19:07:57 2019 TCPv4_CLIENT link remote: [AF_INET]45.95.5.157:1194
Thu Jul  4 19:07:57 2019 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Thu Jul  4 19:08:01 2019 [vpnpfscln] Peer Connection Initiated with [AF_INET]45.95.5.157:1194
Thu Jul  4 19:08:04 2019 do_ifconfig, tt->ipv6=0, tt->did_ifconfig_ipv6_setup=0
Thu Jul  4 19:08:04 2019 /sbin/ifconfig  delete
Thu Jul  4 19:08:04 2019 NOTE: Tried to delete pre-existing tun/tap instance -- No Problem if failure
Thu Jul  4 19:08:04 2019 /sbin/ifconfig  10.0.90.2 10.0.90.2 netmask 255.255.255.0 mtu 1500 up

How I can Fix this issue, Please Suggest.
Thanks.

**Comment by AnhTVc** [comment]
You don't need rebuild lib

Vào Th 5, 4 thg 7, 2019 vào lúc 20:40 cogphone <notifications@github.com>
đã viết:

**Comment by AnhTVc** [comment]
You don't need rebuild lib
