### ISSUE TITLE
Error XCode

### ISSUE THREAD

**Issue by Rimander** [AnhTVc/OpenVPN-IOS#6]
```
Undefined symbols for architecture arm64:
  "_openvpn_main", referenced from:
      ___31-[VPNWrapper startWithOptions:]_block_invoke in VPNWrapper.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

rimander@hotmail.es

**Comment by AnhTVc** [comment]
Build is ready for armv7, if you do not want to build it again try the iphone 5.

**Comment by Rimander** [comment]
I try with my iphone6.
i need export to archive on armv7 and arm64.

I tried to do this.

- Create all Libs x86, arm64, armv7...
- lipo -create libopenvpn_64.a libopenvpnv7.a libopenvpnv7s.a libopenvpnx86.a -output lib_universal.a   yo create a universal lib.
`Undefined symbols for architecture arm64:
  "_openvpn_main", referenced from:`

**Comment by AnhTVc** [comment]
Check: lipo -i libopenvpn.a

**Comment by Rimander** [comment]
ARMV7
`Architectures in the fat file: libopenvpn.a are: armv7`


ARM64
```
input file libopenvpn.a is not a fat file
Non-fat file: libopenvpn.a is architecture: arm64
```

ARMV7
```
input file libopenvpnv.a is not a fat file
Non-fat file: libopenvpnv.a is architecture: armv7
```
